(cl:in-package image_recognition_msgs-msg)
(cl:export '(NOSE-VAL
          NOSE
          NECK-VAL
          NECK
          RIGHT_SHOULDER-VAL
          RIGHT_SHOULDER
          RIGHT_ELBOW-VAL
          RIGHT_ELBOW
          RIGHT_WRIST-VAL
          RIGHT_WRIST
          LEFT_SHOULDER-VAL
          LEFT_SHOULDER
          LEFT_ELBOW-VAL
          LEFT_ELBOW
          LEFT_WRIST-VAL
          LEFT_WRIST
          RIGHT_HIP-VAL
          RIGHT_HIP
          RIGHT_KNEE-VAL
          RIGHT_KNEE
          RIGHT_ANKLE-VAL
          RIGHT_ANKLE
          LEFT_HIP-VAL
          LEFT_HIP
          LEFT_KNEE-VAL
          LEFT_KNEE
          LEFT_ANKLE-VAL
          LEFT_ANKLE
          RIGHT_EYE-VAL
          RIGHT_EYE
          LEFT_EYE-VAL
          LEFT_EYE
          RIGHT_EAR-VAL
          RIGHT_EAR
          LEFT_EAR-VAL
          LEFT_EAR
          CHEST-VAL
          CHEST
))