(cl:defpackage image_recognition_msgs-msg
  (:use )
  (:export
   "<ANNOTATION>"
   "ANNOTATION"
   "<BODYPARTDETECTION>"
   "BODYPARTDETECTION"
   "<CATEGORICALDISTRIBUTION>"
   "CATEGORICALDISTRIBUTION"
   "<CATEGORYPROBABILITY>"
   "CATEGORYPROBABILITY"
   "<FACEPROPERTIES>"
   "FACEPROPERTIES"
   "<PERSONDETECTION>"
   "PERSONDETECTION"
   "<RECOGNITION>"
   "RECOGNITION"
  ))

