// Generated by gencpp from file image_recognition_msgs/BodypartDetection.msg
// DO NOT EDIT!


#ifndef IMAGE_RECOGNITION_MSGS_MESSAGE_BODYPARTDETECTION_H
#define IMAGE_RECOGNITION_MSGS_MESSAGE_BODYPARTDETECTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace image_recognition_msgs
{
template <class ContainerAllocator>
struct BodypartDetection_
{
  typedef BodypartDetection_<ContainerAllocator> Type;

  BodypartDetection_()
    : x(0)
    , y(0)
    , confidence(0.0)  {
    }
  BodypartDetection_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , confidence(0.0)  {
  (void)_alloc;
    }



   typedef uint32_t _x_type;
  _x_type x;

   typedef uint32_t _y_type;
  _y_type y;

   typedef float _confidence_type;
  _confidence_type confidence;




  typedef boost::shared_ptr< ::image_recognition_msgs::BodypartDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::image_recognition_msgs::BodypartDetection_<ContainerAllocator> const> ConstPtr;

}; // struct BodypartDetection_

typedef ::image_recognition_msgs::BodypartDetection_<std::allocator<void> > BodypartDetection;

typedef boost::shared_ptr< ::image_recognition_msgs::BodypartDetection > BodypartDetectionPtr;
typedef boost::shared_ptr< ::image_recognition_msgs::BodypartDetection const> BodypartDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::image_recognition_msgs::BodypartDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::image_recognition_msgs::BodypartDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace image_recognition_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'image_recognition_msgs': ['/home/robot/inmoov_ros/src/image_recognition/image_recognition_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::image_recognition_msgs::BodypartDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::image_recognition_msgs::BodypartDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::image_recognition_msgs::BodypartDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::image_recognition_msgs::BodypartDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::image_recognition_msgs::BodypartDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::image_recognition_msgs::BodypartDetection_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::image_recognition_msgs::BodypartDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2edd10e314180ad374d9e70737f3fc60";
  }

  static const char* value(const ::image_recognition_msgs::BodypartDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2edd10e314180ad3ULL;
  static const uint64_t static_value2 = 0x74d9e70737f3fc60ULL;
};

template<class ContainerAllocator>
struct DataType< ::image_recognition_msgs::BodypartDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "image_recognition_msgs/BodypartDetection";
  }

  static const char* value(const ::image_recognition_msgs::BodypartDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::image_recognition_msgs::BodypartDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 x\n\
uint32 y\n\
float32 confidence\n\
";
  }

  static const char* value(const ::image_recognition_msgs::BodypartDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::image_recognition_msgs::BodypartDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.confidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BodypartDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::image_recognition_msgs::BodypartDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::image_recognition_msgs::BodypartDetection_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.y);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMAGE_RECOGNITION_MSGS_MESSAGE_BODYPARTDETECTION_H
