(cl:defpackage robot_calibration_msgs-msg
  (:use )
  (:export
   "<CALIBRATIONDATA>"
   "CALIBRATIONDATA"
   "<CAMERAPARAMETER>"
   "CAMERAPARAMETER"
   "<CAPTURECONFIG>"
   "CAPTURECONFIG"
   "<EXTENDEDCAMERAINFO>"
   "EXTENDEDCAMERAINFO"
   "<GRIPPERLEDCOMMANDACTION>"
   "GRIPPERLEDCOMMANDACTION"
   "<GRIPPERLEDCOMMANDACTIONFEEDBACK>"
   "GRIPPERLEDCOMMANDACTIONFEEDBACK"
   "<GRIPPERLEDCOMMANDACTIONGOAL>"
   "GRIPPERLEDCOMMANDACTIONGOAL"
   "<GRIPPERLEDCOMMANDACTIONRESULT>"
   "GRIPPERLEDCOMMANDACTIONRESULT"
   "<GRIPPERLEDCOMMANDFEEDBACK>"
   "GRIPPERLEDCOMMANDFEEDBACK"
   "<GRIPPERLEDCOMMANDGOAL>"
   "GRIPPERLEDCOMMANDGOAL"
   "<GRIPPERLEDCOMMANDRESULT>"
   "GRIPPERLEDCOMMANDRESULT"
   "<OBSERVATION>"
   "OBSERVATION"
  ))

