; Auto-generated. Do not edit!


(cl:in-package robot_calibration_msgs-msg)


;//! \htmlinclude GripperLedCommandGoal.msg.html

(cl:defclass <GripperLedCommandGoal> (roslisp-msg-protocol:ros-message)
  ((led_code
    :reader led_code
    :initarg :led_code
    :type cl:fixnum
    :initform 0))
)

(cl:defclass GripperLedCommandGoal (<GripperLedCommandGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GripperLedCommandGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GripperLedCommandGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_calibration_msgs-msg:<GripperLedCommandGoal> is deprecated: use robot_calibration_msgs-msg:GripperLedCommandGoal instead.")))

(cl:ensure-generic-function 'led_code-val :lambda-list '(m))
(cl:defmethod led_code-val ((m <GripperLedCommandGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_calibration_msgs-msg:led_code-val is deprecated.  Use robot_calibration_msgs-msg:led_code instead.")
  (led_code m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GripperLedCommandGoal>) ostream)
  "Serializes a message object of type '<GripperLedCommandGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'led_code)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GripperLedCommandGoal>) istream)
  "Deserializes a message object of type '<GripperLedCommandGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'led_code)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GripperLedCommandGoal>)))
  "Returns string type for a message object of type '<GripperLedCommandGoal>"
  "robot_calibration_msgs/GripperLedCommandGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GripperLedCommandGoal)))
  "Returns string type for a message object of type 'GripperLedCommandGoal"
  "robot_calibration_msgs/GripperLedCommandGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GripperLedCommandGoal>)))
  "Returns md5sum for a message object of type '<GripperLedCommandGoal>"
  "11513917910062a2ca72ae2699b68556")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GripperLedCommandGoal)))
  "Returns md5sum for a message object of type 'GripperLedCommandGoal"
  "11513917910062a2ca72ae2699b68556")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GripperLedCommandGoal>)))
  "Returns full string definition for message of type '<GripperLedCommandGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# This action is used to flash a sequence with LEDs, which can then be detected by calibration~%~%uint8 led_code~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GripperLedCommandGoal)))
  "Returns full string definition for message of type 'GripperLedCommandGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# This action is used to flash a sequence with LEDs, which can then be detected by calibration~%~%uint8 led_code~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GripperLedCommandGoal>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GripperLedCommandGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'GripperLedCommandGoal
    (cl:cons ':led_code (led_code msg))
))
