(cl:in-package haf_grasping-msg)
(cl:export '(INPUT_PC-VAL
          INPUT_PC
          GOAL_FRAME_ID-VAL
          GOAL_FRAME_ID
          GRASP_AREA_CENTER-VAL
          GRASP_AREA_CENTER
          GRASP_AREA_LENGTH_X-VAL
          GRASP_AREA_LENGTH_X
          GRASP_AREA_LENGTH_Y-VAL
          GRASP_AREA_LENGTH_Y
          MAX_CALCULATION_TIME-VAL
          MAX_CALCULATION_TIME
          SHOW_ONLY_BEST_GRASP-VAL
          SHOW_ONLY_BEST_GRASP
          THRESHOLD_GRASP_EVALUATION-VAL
          THRESHOLD_GRASP_EVALUATION
          APPROACH_VECTOR-VAL
          APPROACH_VECTOR
          GRIPPER_OPENING_WIDTH-VAL
          GRIPPER_OPENING_WIDTH
))