int32 servoPin 		#pin number for Servo
int32 sensorPin		#pin number for Sensor
float32 minAngle		#min physical angle of joint
float32 maxAngle		#max physical angle of joint
float32 rest			#rest angle
float32 minPulse		#min Pulse for the servo - physical robot should be at min angle when this is set
float32 maxPulse		#max Pulse for the servo - physical robot should be at max angle when this is set
float32 minSensor		#min reading for sensor
float32 maxSensor		#max reading for sensor
int32 smoothing		#sets default smoothing pattern for joint
float32 maxSpeed		#sets maxspeed




