# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trainergui.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(321, 664)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 120, 301, 511))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.txtMinPulse = QtWidgets.QLineEdit(self.frame)
        self.txtMinPulse.setGeometry(QtCore.QRect(120, 250, 101, 27))
        self.txtMinPulse.setObjectName("txtMinPulse")
        self.txtMaxSensor = QtWidgets.QLineEdit(self.frame)
        self.txtMaxSensor.setGeometry(QtCore.QRect(120, 280, 101, 27))
        self.txtMaxSensor.setObjectName("txtMaxSensor")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(30, 250, 81, 21))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(20, 220, 91, 21))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(30, 310, 81, 21))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(30, 160, 81, 21))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.txtMaxPulse = QtWidgets.QLineEdit(self.frame)
        self.txtMaxPulse.setGeometry(QtCore.QRect(120, 220, 101, 27))
        self.txtMaxPulse.setObjectName("txtMaxPulse")
        self.chkCalibrated = QtWidgets.QCheckBox(self.frame)
        self.chkCalibrated.setGeometry(QtCore.QRect(42, 340, 97, 22))
        self.chkCalibrated.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkCalibrated.setObjectName("chkCalibrated")
        self.txtMaxGoal = QtWidgets.QLineEdit(self.frame)
        self.txtMaxGoal.setGeometry(QtCore.QRect(120, 160, 101, 27))
        self.txtMaxGoal.setObjectName("txtMaxGoal")
        self.txtMinSensor = QtWidgets.QLineEdit(self.frame)
        self.txtMinSensor.setGeometry(QtCore.QRect(120, 310, 101, 27))
        self.txtMinSensor.setObjectName("txtMinSensor")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(50, 190, 61, 21))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.cmbSmoothing = QtWidgets.QComboBox(self.frame)
        self.cmbSmoothing.setEnabled(True)
        self.cmbSmoothing.setGeometry(QtCore.QRect(122, 110, 101, 27))
        self.cmbSmoothing.setObjectName("cmbSmoothing")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setEnabled(False)
        self.label_8.setGeometry(QtCore.QRect(28, 80, 81, 21))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.txtMaxSpeed = QtWidgets.QLineEdit(self.frame)
        self.txtMaxSpeed.setEnabled(True)
        self.txtMaxSpeed.setGeometry(QtCore.QRect(122, 80, 101, 27))
        self.txtMaxSpeed.setReadOnly(True)
        self.txtMaxSpeed.setObjectName("txtMaxSpeed")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(30, 280, 81, 21))
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setEnabled(False)
        self.label_14.setGeometry(QtCore.QRect(22, 110, 91, 21))
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.txtMinGoal = QtWidgets.QLineEdit(self.frame)
        self.txtMinGoal.setGeometry(QtCore.QRect(120, 190, 101, 27))
        self.txtMinGoal.setObjectName("txtMinGoal")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(30, 470, 81, 16))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.txtSpeed = QtWidgets.QLineEdit(self.frame)
        self.txtSpeed.setEnabled(True)
        self.txtSpeed.setGeometry(QtCore.QRect(140, 430, 81, 27))
        self.txtSpeed.setReadOnly(True)
        self.txtSpeed.setObjectName("txtSpeed")
        self.chkPower = QtWidgets.QCheckBox(self.frame)
        self.chkPower.setEnabled(True)
        self.chkPower.setGeometry(QtCore.QRect(42, 410, 97, 22))
        self.chkPower.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkPower.setText("")
        self.chkPower.setCheckable(False)
        self.chkPower.setObjectName("chkPower")
        self.txtPosition = QtWidgets.QLineEdit(self.frame)
        self.txtPosition.setEnabled(True)
        self.txtPosition.setGeometry(QtCore.QRect(122, 380, 101, 27))
        self.txtPosition.setReadOnly(True)
        self.txtPosition.setObjectName("txtPosition")
        self.txtSensorRaw = QtWidgets.QLineEdit(self.frame)
        self.txtSensorRaw.setEnabled(True)
        self.txtSensorRaw.setGeometry(QtCore.QRect(124, 470, 101, 27))
        self.txtSensorRaw.setReadOnly(True)
        self.txtSensorRaw.setObjectName("txtSensorRaw")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(52, 380, 61, 21))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(22, 410, 91, 17))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.chkEnabled = QtWidgets.QCheckBox(self.frame)
        self.chkEnabled.setGeometry(QtCore.QRect(42, 10, 97, 22))
        self.chkEnabled.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkEnabled.setObjectName("chkEnabled")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(52, 40, 61, 21))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.txtGoal = QtWidgets.QLineEdit(self.frame)
        self.txtGoal.setGeometry(QtCore.QRect(122, 40, 101, 27))
        self.txtGoal.setObjectName("txtGoal")
        self.chkMoving = QtWidgets.QCheckBox(self.frame)
        self.chkMoving.setEnabled(True)
        self.chkMoving.setGeometry(QtCore.QRect(42, 430, 97, 22))
        self.chkMoving.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkMoving.setText("")
        self.chkMoving.setCheckable(False)
        self.chkMoving.setObjectName("chkMoving")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(20, 430, 91, 17))
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.sliderGoal = QtWidgets.QSlider(self.frame)
        self.sliderGoal.setGeometry(QtCore.QRect(260, 10, 31, 491))
        self.sliderGoal.setMaximum(990000)
        self.sliderGoal.setSingleStep(10000)
        self.sliderGoal.setPageStep(100000)
        self.sliderGoal.setOrientation(QtCore.Qt.Vertical)
        self.sliderGoal.setInvertedAppearance(False)
        self.sliderGoal.setInvertedControls(False)
        self.sliderGoal.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.sliderGoal.setTickInterval(10000)
        self.sliderGoal.setObjectName("sliderGoal")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(-10, 50, 71, 21))
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(-10, 80, 71, 21))
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.cmbBus = QtWidgets.QComboBox(self.centralwidget)
        self.cmbBus.setGeometry(QtCore.QRect(70, 50, 241, 27))
        self.cmbBus.setFrame(True)
        self.cmbBus.setObjectName("cmbBus")
        self.cmbServo = QtWidgets.QComboBox(self.centralwidget)
        self.cmbServo.setGeometry(QtCore.QRect(70, 80, 241, 27))
        self.cmbServo.setObjectName("cmbServo")
        self.chkEnableAll = QtWidgets.QCheckBox(self.centralwidget)
        self.chkEnableAll.setGeometry(QtCore.QRect(190, 10, 121, 22))
        self.chkEnableAll.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkEnableAll.setObjectName("chkEnableAll")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.chkEnabled, self.txtGoal)
        MainWindow.setTabOrder(self.txtGoal, self.txtMaxSpeed)
        MainWindow.setTabOrder(self.txtMaxSpeed, self.cmbSmoothing)
        MainWindow.setTabOrder(self.cmbSmoothing, self.txtMinGoal)
        MainWindow.setTabOrder(self.txtMinGoal, self.txtMaxGoal)
        MainWindow.setTabOrder(self.txtMaxGoal, self.txtMinPulse)
        MainWindow.setTabOrder(self.txtMinPulse, self.txtMaxPulse)
        MainWindow.setTabOrder(self.txtMaxPulse, self.txtMinSensor)
        MainWindow.setTabOrder(self.txtMinSensor, self.txtMaxSensor)
        MainWindow.setTabOrder(self.txtMaxSensor, self.chkCalibrated)
        MainWindow.setTabOrder(self.chkCalibrated, self.txtPosition)
        MainWindow.setTabOrder(self.txtPosition, self.chkPower)
        MainWindow.setTabOrder(self.chkPower, self.chkMoving)
        MainWindow.setTabOrder(self.chkMoving, self.txtSpeed)
        MainWindow.setTabOrder(self.txtSpeed, self.txtSensorRaw)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ROS Servo Trainer"))
        self.label_3.setText(_translate("MainWindow", "Min Pulse"))
        self.label_4.setText(_translate("MainWindow", "Max Pulse"))
        self.label_5.setText(_translate("MainWindow", "MinSensor"))
        self.label_2.setText(_translate("MainWindow", "Max Goal"))
        self.chkCalibrated.setText(_translate("MainWindow", "Calibrated"))
        self.label.setText(_translate("MainWindow", "Min Goal"))
        self.label_8.setText(_translate("MainWindow", "MaxSpeed"))
        self.label_6.setText(_translate("MainWindow", "Max Sensor"))
        self.label_14.setText(_translate("MainWindow", "Smoothing"))
        self.label_7.setText(_translate("MainWindow", "Sensor Raw"))
        self.label_10.setText(_translate("MainWindow", "Position"))
        self.label_11.setText(_translate("MainWindow", "Power"))
        self.chkEnabled.setText(_translate("MainWindow", "Enabled"))
        self.label_9.setText(_translate("MainWindow", "Goal"))
        self.label_15.setText(_translate("MainWindow", "Moving"))
        self.label_12.setText(_translate("MainWindow", "Bus"))
        self.label_13.setText(_translate("MainWindow", "Servo"))
        self.chkEnableAll.setText(_translate("MainWindow", "Enable All"))

