# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lookgui.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(617, 415)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.chkEnable = QtWidgets.QCheckBox(self.centralwidget)
        self.chkEnable.setGeometry(QtCore.QRect(440, 10, 97, 22))
        self.chkEnable.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkEnable.setObjectName("chkEnable")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 40, 521, 311))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(320, 10, 111, 20))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(310, 30, 121, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(320, 50, 111, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(330, 70, 101, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(350, 90, 81, 17))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(340, 110, 91, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(330, 130, 101, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(440, 10, 71, 17))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(440, 30, 71, 17))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(440, 50, 71, 17))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(440, 70, 71, 17))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(440, 90, 71, 17))
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(440, 110, 71, 21))
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(440, 130, 71, 21))
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.radioLookAround = QtWidgets.QRadioButton(self.frame)
        self.radioLookAround.setGeometry(QtCore.QRect(10, 10, 117, 22))
        self.radioLookAround.setChecked(True)
        self.radioLookAround.setObjectName("radioLookAround")
        self.radioLookOut = QtWidgets.QRadioButton(self.frame)
        self.radioLookOut.setGeometry(QtCore.QRect(10, 30, 117, 22))
        self.radioLookOut.setObjectName("radioLookOut")
        self.radioSpeaking = QtWidgets.QRadioButton(self.frame)
        self.radioSpeaking.setGeometry(QtCore.QRect(10, 50, 117, 22))
        self.radioSpeaking.setObjectName("radioSpeaking")
        self.radioPunch = QtWidgets.QRadioButton(self.frame)
        self.radioPunch.setGeometry(QtCore.QRect(10, 70, 181, 22))
        self.radioPunch.setObjectName("radioPunch")
        self.radioBoxerJab = QtWidgets.QRadioButton(self.frame)
        self.radioBoxerJab.setGeometry(QtCore.QRect(10, 90, 161, 22))
        self.radioBoxerJab.setObjectName("radioBoxerJab")
        self.radioBoxerGuard = QtWidgets.QRadioButton(self.frame)
        self.radioBoxerGuard.setGeometry(QtCore.QRect(10, 110, 161, 22))
        self.radioBoxerGuard.setObjectName("radioBoxerGuard")
        self.radioBeverage = QtWidgets.QRadioButton(self.frame)
        self.radioBeverage.setGeometry(QtCore.QRect(10, 130, 161, 22))
        self.radioBeverage.setObjectName("radioBeverage")
        self.sliderX = QtWidgets.QSlider(self.frame)
        self.sliderX.setGeometry(QtCore.QRect(10, 200, 501, 22))
        self.sliderX.setMaximum(100)
        self.sliderX.setProperty("value", 60)
        self.sliderX.setSliderPosition(60)
        self.sliderX.setOrientation(QtCore.Qt.Horizontal)
        self.sliderX.setObjectName("sliderX")
        self.sliderY = QtWidgets.QSlider(self.frame)
        self.sliderY.setGeometry(QtCore.QRect(250, 120, 22, 181))
        self.sliderY.setMaximum(100)
        self.sliderY.setProperty("value", 50)
        self.sliderY.setOrientation(QtCore.Qt.Vertical)
        self.sliderY.setObjectName("sliderY")
        self.radioArmOut = QtWidgets.QRadioButton(self.frame)
        self.radioArmOut.setGeometry(QtCore.QRect(10, 150, 161, 22))
        self.radioArmOut.setObjectName("radioArmOut")
        self.chkFlipX = QtWidgets.QCheckBox(self.centralwidget)
        self.chkFlipX.setGeometry(QtCore.QRect(30, 10, 97, 21))
        self.chkFlipX.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkFlipX.setObjectName("chkFlipX")
        self.chkFlipY = QtWidgets.QCheckBox(self.centralwidget)
        self.chkFlipY.setGeometry(QtCore.QRect(110, 10, 97, 21))
        self.chkFlipY.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkFlipY.setObjectName("chkFlipY")
        self.chkRandom = QtWidgets.QCheckBox(self.centralwidget)
        self.chkRandom.setGeometry(QtCore.QRect(190, 10, 97, 21))
        self.chkRandom.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkRandom.setObjectName("chkRandom")
        self.sliderOut = QtWidgets.QSlider(self.centralwidget)
        self.sliderOut.setGeometry(QtCore.QRect(560, 40, 22, 311))
        self.sliderOut.setMinimum(0)
        self.sliderOut.setMaximum(100)
        self.sliderOut.setProperty("value", 0)
        self.sliderOut.setOrientation(QtCore.Qt.Vertical)
        self.sliderOut.setObjectName("sliderOut")
        self.sliderGrasp = QtWidgets.QSlider(self.centralwidget)
        self.sliderGrasp.setGeometry(QtCore.QRect(20, 370, 521, 22))
        self.sliderGrasp.setMaximum(100)
        self.sliderGrasp.setProperty("value", 0)
        self.sliderGrasp.setOrientation(QtCore.Qt.Horizontal)
        self.sliderGrasp.setObjectName("sliderGrasp")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Look At"))
        self.chkEnable.setText(_translate("MainWindow", "Enable"))
        self.label.setText(_translate("MainWindow", "Eyes Left Right"))
        self.label_2.setText(_translate("MainWindow", "Eyes Up Down"))
        self.label_3.setText(_translate("MainWindow", "Head Left Right"))
        self.label_4.setText(_translate("MainWindow", "Head Up Down"))
        self.label_5.setText(_translate("MainWindow", "HeadTilt"))
        self.label_6.setText(_translate("MainWindow", "Waist Rotate"))
        self.label_7.setText(_translate("MainWindow", "Waist Tilt"))
        self.label_8.setText(_translate("MainWindow", "TextLabel"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "TextLabel"))
        self.label_11.setText(_translate("MainWindow", "TextLabel"))
        self.label_12.setText(_translate("MainWindow", "TextLabel"))
        self.label_13.setText(_translate("MainWindow", "TextLabel"))
        self.label_14.setText(_translate("MainWindow", "TextLabel"))
        self.radioLookAround.setText(_translate("MainWindow", "Look Around"))
        self.radioLookOut.setText(_translate("MainWindow", "Look Out"))
        self.radioSpeaking.setText(_translate("MainWindow", "Speaking"))
        self.radioPunch.setText(_translate("MainWindow", "Boxer - Punch"))
        self.radioBoxerJab.setText(_translate("MainWindow", "Boxer - Jab"))
        self.radioBoxerGuard.setText(_translate("MainWindow", "Boxer - Guard"))
        self.radioBeverage.setText(_translate("MainWindow", "Get me a Beverage"))
        self.radioArmOut.setText(_translate("MainWindow", "Arm Out"))
        self.chkFlipX.setText(_translate("MainWindow", "Flip X"))
        self.chkFlipY.setText(_translate("MainWindow", "Flip Y"))
        self.chkRandom.setText(_translate("MainWindow", "Random"))

