// Generated by gencpp from file haf_grasping/GraspSearchCenter.msg
// DO NOT EDIT!


#ifndef HAF_GRASPING_MESSAGE_GRASPSEARCHCENTER_H
#define HAF_GRASPING_MESSAGE_GRASPSEARCHCENTER_H

#include <ros/service_traits.h>


#include <haf_grasping/GraspSearchCenterRequest.h>
#include <haf_grasping/GraspSearchCenterResponse.h>


namespace haf_grasping
{

struct GraspSearchCenter
{

typedef GraspSearchCenterRequest Request;
typedef GraspSearchCenterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GraspSearchCenter
} // namespace haf_grasping


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::haf_grasping::GraspSearchCenter > {
  static const char* value()
  {
    return "2e7151a3ec270e58847862555bffd4c4";
  }

  static const char* value(const ::haf_grasping::GraspSearchCenter&) { return value(); }
};

template<>
struct DataType< ::haf_grasping::GraspSearchCenter > {
  static const char* value()
  {
    return "haf_grasping/GraspSearchCenter";
  }

  static const char* value(const ::haf_grasping::GraspSearchCenter&) { return value(); }
};


// service_traits::MD5Sum< ::haf_grasping::GraspSearchCenterRequest> should match 
// service_traits::MD5Sum< ::haf_grasping::GraspSearchCenter > 
template<>
struct MD5Sum< ::haf_grasping::GraspSearchCenterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::haf_grasping::GraspSearchCenter >::value();
  }
  static const char* value(const ::haf_grasping::GraspSearchCenterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::haf_grasping::GraspSearchCenterRequest> should match 
// service_traits::DataType< ::haf_grasping::GraspSearchCenter > 
template<>
struct DataType< ::haf_grasping::GraspSearchCenterRequest>
{
  static const char* value()
  {
    return DataType< ::haf_grasping::GraspSearchCenter >::value();
  }
  static const char* value(const ::haf_grasping::GraspSearchCenterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::haf_grasping::GraspSearchCenterResponse> should match 
// service_traits::MD5Sum< ::haf_grasping::GraspSearchCenter > 
template<>
struct MD5Sum< ::haf_grasping::GraspSearchCenterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::haf_grasping::GraspSearchCenter >::value();
  }
  static const char* value(const ::haf_grasping::GraspSearchCenterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::haf_grasping::GraspSearchCenterResponse> should match 
// service_traits::DataType< ::haf_grasping::GraspSearchCenter > 
template<>
struct DataType< ::haf_grasping::GraspSearchCenterResponse>
{
  static const char* value()
  {
    return DataType< ::haf_grasping::GraspSearchCenter >::value();
  }
  static const char* value(const ::haf_grasping::GraspSearchCenterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HAF_GRASPING_MESSAGE_GRASPSEARCHCENTER_H
