// Generated by gencpp from file haf_grasping/GraspSearchCenterRequest.msg
// DO NOT EDIT!


#ifndef HAF_GRASPING_MESSAGE_GRASPSEARCHCENTERREQUEST_H
#define HAF_GRASPING_MESSAGE_GRASPSEARCHCENTERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace haf_grasping
{
template <class ContainerAllocator>
struct GraspSearchCenterRequest_
{
  typedef GraspSearchCenterRequest_<ContainerAllocator> Type;

  GraspSearchCenterRequest_()
    : graspsearchcenter()  {
    }
  GraspSearchCenterRequest_(const ContainerAllocator& _alloc)
    : graspsearchcenter(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _graspsearchcenter_type;
  _graspsearchcenter_type graspsearchcenter;




  typedef boost::shared_ptr< ::haf_grasping::GraspSearchCenterRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::haf_grasping::GraspSearchCenterRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GraspSearchCenterRequest_

typedef ::haf_grasping::GraspSearchCenterRequest_<std::allocator<void> > GraspSearchCenterRequest;

typedef boost::shared_ptr< ::haf_grasping::GraspSearchCenterRequest > GraspSearchCenterRequestPtr;
typedef boost::shared_ptr< ::haf_grasping::GraspSearchCenterRequest const> GraspSearchCenterRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::haf_grasping::GraspSearchCenterRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::haf_grasping::GraspSearchCenterRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace haf_grasping

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg'], 'actionlib': ['/opt/ros/kinetic/share/actionlib/cmake/../msg'], 'haf_grasping': ['/home/robot/inmoov_ros/src/haf_grasping/msg', '/home/robot/inmoov_ros/devel/share/haf_grasping/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::haf_grasping::GraspSearchCenterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::haf_grasping::GraspSearchCenterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::haf_grasping::GraspSearchCenterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::haf_grasping::GraspSearchCenterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::haf_grasping::GraspSearchCenterRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::haf_grasping::GraspSearchCenterRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::haf_grasping::GraspSearchCenterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8ea95ef8571fb59e1b8121fdcd68963c";
  }

  static const char* value(const ::haf_grasping::GraspSearchCenterRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8ea95ef8571fb59eULL;
  static const uint64_t static_value2 = 0x1b8121fdcd68963cULL;
};

template<class ContainerAllocator>
struct DataType< ::haf_grasping::GraspSearchCenterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "haf_grasping/GraspSearchCenterRequest";
  }

  static const char* value(const ::haf_grasping::GraspSearchCenterRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::haf_grasping::GraspSearchCenterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point graspsearchcenter\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::haf_grasping::GraspSearchCenterRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::haf_grasping::GraspSearchCenterRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.graspsearchcenter);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GraspSearchCenterRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::haf_grasping::GraspSearchCenterRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::haf_grasping::GraspSearchCenterRequest_<ContainerAllocator>& v)
  {
    s << indent << "graspsearchcenter: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.graspsearchcenter);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAF_GRASPING_MESSAGE_GRASPSEARCHCENTERREQUEST_H
