// Generated by gencpp from file haf_grasping/GraspCalculationTimeMaxResponse.msg
// DO NOT EDIT!


#ifndef HAF_GRASPING_MESSAGE_GRASPCALCULATIONTIMEMAXRESPONSE_H
#define HAF_GRASPING_MESSAGE_GRASPCALCULATIONTIMEMAXRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace haf_grasping
{
template <class ContainerAllocator>
struct GraspCalculationTimeMaxResponse_
{
  typedef GraspCalculationTimeMaxResponse_<ContainerAllocator> Type;

  GraspCalculationTimeMaxResponse_()
    : result(false)  {
    }
  GraspCalculationTimeMaxResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;




  typedef boost::shared_ptr< ::haf_grasping::GraspCalculationTimeMaxResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::haf_grasping::GraspCalculationTimeMaxResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GraspCalculationTimeMaxResponse_

typedef ::haf_grasping::GraspCalculationTimeMaxResponse_<std::allocator<void> > GraspCalculationTimeMaxResponse;

typedef boost::shared_ptr< ::haf_grasping::GraspCalculationTimeMaxResponse > GraspCalculationTimeMaxResponsePtr;
typedef boost::shared_ptr< ::haf_grasping::GraspCalculationTimeMaxResponse const> GraspCalculationTimeMaxResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::haf_grasping::GraspCalculationTimeMaxResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::haf_grasping::GraspCalculationTimeMaxResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace haf_grasping

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg'], 'actionlib': ['/opt/ros/kinetic/share/actionlib/cmake/../msg'], 'haf_grasping': ['/home/robot/inmoov_ros/src/haf_grasping/msg', '/home/robot/inmoov_ros/devel/share/haf_grasping/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::haf_grasping::GraspCalculationTimeMaxResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::haf_grasping::GraspCalculationTimeMaxResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::haf_grasping::GraspCalculationTimeMaxResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::haf_grasping::GraspCalculationTimeMaxResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::haf_grasping::GraspCalculationTimeMaxResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::haf_grasping::GraspCalculationTimeMaxResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::haf_grasping::GraspCalculationTimeMaxResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::haf_grasping::GraspCalculationTimeMaxResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::haf_grasping::GraspCalculationTimeMaxResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "haf_grasping/GraspCalculationTimeMaxResponse";
  }

  static const char* value(const ::haf_grasping::GraspCalculationTimeMaxResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::haf_grasping::GraspCalculationTimeMaxResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n\
\n\
";
  }

  static const char* value(const ::haf_grasping::GraspCalculationTimeMaxResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::haf_grasping::GraspCalculationTimeMaxResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GraspCalculationTimeMaxResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::haf_grasping::GraspCalculationTimeMaxResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::haf_grasping::GraspCalculationTimeMaxResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAF_GRASPING_MESSAGE_GRASPCALCULATIONTIMEMAXRESPONSE_H
