(cl:defpackage moveit_simple_grasps-msg
  (:use )
  (:export
   "<GENERATEGRASPSACTION>"
   "GENERATEGRASPSACTION"
   "<GENERATEGRASPSACTIONFEEDBACK>"
   "GENERATEGRASPSACTIONFEEDBACK"
   "<GENERATEGRASPSACTIONGOAL>"
   "GENERATEGRASPSACTIONGOAL"
   "<GENERATEGRASPSACTIONRESULT>"
   "GENERATEGRASPSACTIONRESULT"
   "<GENERATEGRASPSFEEDBACK>"
   "GENERATEGRASPSFEEDBACK"
   "<GENERATEGRASPSGOAL>"
   "GENERATEGRASPSGOAL"
   "<GENERATEGRASPSRESULT>"
   "GENERATEGRASPSRESULT"
   "<GRASPGENERATOROPTIONS>"
   "GRASPGENERATOROPTIONS"
  ))

