(cl:defpackage inmoov_msgs-msg
  (:use )
  (:export
   "<LEAPFRAME>"
   "LEAPFRAME"
   "<LEAPGESTURE>"
   "LEAPGESTURE"
   "<LEAPHAND>"
   "LEAPHAND"
   "<LEAPPOINTABLE>"
   "LEAPPOINTABLE"
   "<MOTORCOMMAND>"
   "MOTORCOMMAND"
   "<MOTORSTATUS>"
   "MOTORSTATUS"
   "<NEOPIXEL>"
   "NEOPIXEL"
   "<NEOPIXEL_COMMAND>"
   "NEOPIXEL_COMMAND"
   "<SERVOSETUP>"
   "SERVOSETUP"
   "<STATUS>"
   "STATUS"
  ))

