(cl:in-package inmoov_msgs-msg)
(cl:export '(JOINT-VAL
          JOINT
          BUS-VAL
          BUS
          SERVOPIN-VAL
          SERVOPIN
          GOAL-VAL
          GOAL
          POSITION-VAL
          POSITION
          SMOOTH-VAL
          SMOOTH
          MAXSPEED-VAL
          MAXSPEED
          PRESENTSPEED-VAL
          PRESENTSPEED
          MOVING-VAL
          MOVING
          POSRAW-VAL
          POSRAW
          ENABLED-VAL
          ENABLED
          POWER-VAL
          POWER
          DEBUG1-VAL
          DEBUG1
          DEBUG2-VAL
          DEBUG2
          DEBUG3-VAL
          DEBUG3
))