// Generated by gencpp from file inmoov_msgs/inmoov_voiceRequest.msg
// DO NOT EDIT!


#ifndef INMOOV_MSGS_MESSAGE_INMOOV_VOICEREQUEST_H
#define INMOOV_MSGS_MESSAGE_INMOOV_VOICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace inmoov_msgs
{
template <class ContainerAllocator>
struct inmoov_voiceRequest_
{
  typedef inmoov_voiceRequest_<ContainerAllocator> Type;

  inmoov_voiceRequest_()
    : toSpeak()  {
    }
  inmoov_voiceRequest_(const ContainerAllocator& _alloc)
    : toSpeak(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _toSpeak_type;
  _toSpeak_type toSpeak;




  typedef boost::shared_ptr< ::inmoov_msgs::inmoov_voiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::inmoov_msgs::inmoov_voiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct inmoov_voiceRequest_

typedef ::inmoov_msgs::inmoov_voiceRequest_<std::allocator<void> > inmoov_voiceRequest;

typedef boost::shared_ptr< ::inmoov_msgs::inmoov_voiceRequest > inmoov_voiceRequestPtr;
typedef boost::shared_ptr< ::inmoov_msgs::inmoov_voiceRequest const> inmoov_voiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::inmoov_msgs::inmoov_voiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::inmoov_msgs::inmoov_voiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace inmoov_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'inmoov_msgs': ['/home/robot/inmoov_ros/src/inmoov_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::inmoov_msgs::inmoov_voiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::inmoov_msgs::inmoov_voiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inmoov_msgs::inmoov_voiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inmoov_msgs::inmoov_voiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inmoov_msgs::inmoov_voiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inmoov_msgs::inmoov_voiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::inmoov_msgs::inmoov_voiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ba4097947dc3268535058396d9ee182";
  }

  static const char* value(const ::inmoov_msgs::inmoov_voiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ba4097947dc3268ULL;
  static const uint64_t static_value2 = 0x535058396d9ee182ULL;
};

template<class ContainerAllocator>
struct DataType< ::inmoov_msgs::inmoov_voiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "inmoov_msgs/inmoov_voiceRequest";
  }

  static const char* value(const ::inmoov_msgs::inmoov_voiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::inmoov_msgs::inmoov_voiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string   toSpeak\n\
";
  }

  static const char* value(const ::inmoov_msgs::inmoov_voiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::inmoov_msgs::inmoov_voiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.toSpeak);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct inmoov_voiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::inmoov_msgs::inmoov_voiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::inmoov_msgs::inmoov_voiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "toSpeak: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.toSpeak);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INMOOV_MSGS_MESSAGE_INMOOV_VOICEREQUEST_H
