// Generated by gencpp from file inmoov_msgs/inmoov_sound_playResponse.msg
// DO NOT EDIT!


#ifndef INMOOV_MSGS_MESSAGE_INMOOV_SOUND_PLAYRESPONSE_H
#define INMOOV_MSGS_MESSAGE_INMOOV_SOUND_PLAYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace inmoov_msgs
{
template <class ContainerAllocator>
struct inmoov_sound_playResponse_
{
  typedef inmoov_sound_playResponse_<ContainerAllocator> Type;

  inmoov_sound_playResponse_()
    : data(0.0)  {
    }
  inmoov_sound_playResponse_(const ContainerAllocator& _alloc)
    : data(0.0)  {
  (void)_alloc;
    }



   typedef float _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::inmoov_msgs::inmoov_sound_playResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::inmoov_msgs::inmoov_sound_playResponse_<ContainerAllocator> const> ConstPtr;

}; // struct inmoov_sound_playResponse_

typedef ::inmoov_msgs::inmoov_sound_playResponse_<std::allocator<void> > inmoov_sound_playResponse;

typedef boost::shared_ptr< ::inmoov_msgs::inmoov_sound_playResponse > inmoov_sound_playResponsePtr;
typedef boost::shared_ptr< ::inmoov_msgs::inmoov_sound_playResponse const> inmoov_sound_playResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::inmoov_msgs::inmoov_sound_playResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::inmoov_msgs::inmoov_sound_playResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace inmoov_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'inmoov_msgs': ['/home/robot/inmoov_ros/src/inmoov_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::inmoov_msgs::inmoov_sound_playResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::inmoov_msgs::inmoov_sound_playResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inmoov_msgs::inmoov_sound_playResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inmoov_msgs::inmoov_sound_playResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inmoov_msgs::inmoov_sound_playResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inmoov_msgs::inmoov_sound_playResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::inmoov_msgs::inmoov_sound_playResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "73fcbf46b49191e672908e50842a83d4";
  }

  static const char* value(const ::inmoov_msgs::inmoov_sound_playResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x73fcbf46b49191e6ULL;
  static const uint64_t static_value2 = 0x72908e50842a83d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::inmoov_msgs::inmoov_sound_playResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "inmoov_msgs/inmoov_sound_playResponse";
  }

  static const char* value(const ::inmoov_msgs::inmoov_sound_playResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::inmoov_msgs::inmoov_sound_playResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 data\n\
\n\
";
  }

  static const char* value(const ::inmoov_msgs::inmoov_sound_playResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::inmoov_msgs::inmoov_sound_playResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct inmoov_sound_playResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::inmoov_msgs::inmoov_sound_playResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::inmoov_msgs::inmoov_sound_playResponse_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<float>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INMOOV_MSGS_MESSAGE_INMOOV_SOUND_PLAYRESPONSE_H
