// Generated by gencpp from file inmoov_msgs/MotorCommand.msg
// DO NOT EDIT!


#ifndef INMOOV_MSGS_MESSAGE_MOTORCOMMAND_H
#define INMOOV_MSGS_MESSAGE_MOTORCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace inmoov_msgs
{
template <class ContainerAllocator>
struct MotorCommand_
{
  typedef MotorCommand_<ContainerAllocator> Type;

  MotorCommand_()
    : id(0)
    , parameter(0)
    , value(0.0)  {
    }
  MotorCommand_(const ContainerAllocator& _alloc)
    : id(0)
    , parameter(0)
    , value(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef uint8_t _parameter_type;
  _parameter_type parameter;

   typedef float _value_type;
  _value_type value;




  typedef boost::shared_ptr< ::inmoov_msgs::MotorCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::inmoov_msgs::MotorCommand_<ContainerAllocator> const> ConstPtr;

}; // struct MotorCommand_

typedef ::inmoov_msgs::MotorCommand_<std::allocator<void> > MotorCommand;

typedef boost::shared_ptr< ::inmoov_msgs::MotorCommand > MotorCommandPtr;
typedef boost::shared_ptr< ::inmoov_msgs::MotorCommand const> MotorCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::inmoov_msgs::MotorCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::inmoov_msgs::MotorCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace inmoov_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'inmoov_msgs': ['/home/robot/inmoov_ros/src/inmoov_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::inmoov_msgs::MotorCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::inmoov_msgs::MotorCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inmoov_msgs::MotorCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inmoov_msgs::MotorCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inmoov_msgs::MotorCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inmoov_msgs::MotorCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::inmoov_msgs::MotorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb0b08dd62a5eaff08551ecb80949ef6";
  }

  static const char* value(const ::inmoov_msgs::MotorCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb0b08dd62a5eaffULL;
  static const uint64_t static_value2 = 0x08551ecb80949ef6ULL;
};

template<class ContainerAllocator>
struct DataType< ::inmoov_msgs::MotorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "inmoov_msgs/MotorCommand";
  }

  static const char* value(const ::inmoov_msgs::MotorCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::inmoov_msgs::MotorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8   id                      # motor id\n\
uint8   parameter               # parameter\n\
float32 value			# value\n\
\n\
";
  }

  static const char* value(const ::inmoov_msgs::MotorCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::inmoov_msgs::MotorCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.parameter);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MotorCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::inmoov_msgs::MotorCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::inmoov_msgs::MotorCommand_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "parameter: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.parameter);
    s << indent << "value: ";
    Printer<float>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INMOOV_MSGS_MESSAGE_MOTORCOMMAND_H
