// Generated by gencpp from file inmoov_msgs/NeoPixel_command.msg
// DO NOT EDIT!


#ifndef INMOOV_MSGS_MESSAGE_NEOPIXEL_COMMAND_H
#define INMOOV_MSGS_MESSAGE_NEOPIXEL_COMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace inmoov_msgs
{
template <class ContainerAllocator>
struct NeoPixel_command_
{
  typedef NeoPixel_command_<ContainerAllocator> Type;

  NeoPixel_command_()
    : displayType()
    , wait(0)
    , red(0)
    , green(0)
    , blue(0)
    , red2(0)
    , green2(0)
    , blue2(0)  {
    }
  NeoPixel_command_(const ContainerAllocator& _alloc)
    : displayType(_alloc)
    , wait(0)
    , red(0)
    , green(0)
    , blue(0)
    , red2(0)
    , green2(0)
    , blue2(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _displayType_type;
  _displayType_type displayType;

   typedef int32_t _wait_type;
  _wait_type wait;

   typedef int32_t _red_type;
  _red_type red;

   typedef int32_t _green_type;
  _green_type green;

   typedef int32_t _blue_type;
  _blue_type blue;

   typedef int32_t _red2_type;
  _red2_type red2;

   typedef int32_t _green2_type;
  _green2_type green2;

   typedef int32_t _blue2_type;
  _blue2_type blue2;




  typedef boost::shared_ptr< ::inmoov_msgs::NeoPixel_command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::inmoov_msgs::NeoPixel_command_<ContainerAllocator> const> ConstPtr;

}; // struct NeoPixel_command_

typedef ::inmoov_msgs::NeoPixel_command_<std::allocator<void> > NeoPixel_command;

typedef boost::shared_ptr< ::inmoov_msgs::NeoPixel_command > NeoPixel_commandPtr;
typedef boost::shared_ptr< ::inmoov_msgs::NeoPixel_command const> NeoPixel_commandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::inmoov_msgs::NeoPixel_command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::inmoov_msgs::NeoPixel_command_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace inmoov_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'inmoov_msgs': ['/home/robot/inmoov_ros/src/inmoov_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::inmoov_msgs::NeoPixel_command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::inmoov_msgs::NeoPixel_command_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inmoov_msgs::NeoPixel_command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inmoov_msgs::NeoPixel_command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inmoov_msgs::NeoPixel_command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inmoov_msgs::NeoPixel_command_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::inmoov_msgs::NeoPixel_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "101f9c07dca2c5b64e40edc6e84d3160";
  }

  static const char* value(const ::inmoov_msgs::NeoPixel_command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x101f9c07dca2c5b6ULL;
  static const uint64_t static_value2 = 0x4e40edc6e84d3160ULL;
};

template<class ContainerAllocator>
struct DataType< ::inmoov_msgs::NeoPixel_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "inmoov_msgs/NeoPixel_command";
  }

  static const char* value(const ::inmoov_msgs::NeoPixel_command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::inmoov_msgs::NeoPixel_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string displayType\n\
int32 wait\n\
int32 red\n\
int32 green\n\
int32 blue\n\
int32 red2\n\
int32 green2\n\
int32 blue2\n\
\n\
\n\
\n\
";
  }

  static const char* value(const ::inmoov_msgs::NeoPixel_command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::inmoov_msgs::NeoPixel_command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.displayType);
      stream.next(m.wait);
      stream.next(m.red);
      stream.next(m.green);
      stream.next(m.blue);
      stream.next(m.red2);
      stream.next(m.green2);
      stream.next(m.blue2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NeoPixel_command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::inmoov_msgs::NeoPixel_command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::inmoov_msgs::NeoPixel_command_<ContainerAllocator>& v)
  {
    s << indent << "displayType: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.displayType);
    s << indent << "wait: ";
    Printer<int32_t>::stream(s, indent + "  ", v.wait);
    s << indent << "red: ";
    Printer<int32_t>::stream(s, indent + "  ", v.red);
    s << indent << "green: ";
    Printer<int32_t>::stream(s, indent + "  ", v.green);
    s << indent << "blue: ";
    Printer<int32_t>::stream(s, indent + "  ", v.blue);
    s << indent << "red2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.red2);
    s << indent << "green2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.green2);
    s << indent << "blue2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.blue2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INMOOV_MSGS_MESSAGE_NEOPIXEL_COMMAND_H
