// Generated by gencpp from file inmoov_msgs/NeoPixelSetBrightnessRequest.msg
// DO NOT EDIT!


#ifndef INMOOV_MSGS_MESSAGE_NEOPIXELSETBRIGHTNESSREQUEST_H
#define INMOOV_MSGS_MESSAGE_NEOPIXELSETBRIGHTNESSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace inmoov_msgs
{
template <class ContainerAllocator>
struct NeoPixelSetBrightnessRequest_
{
  typedef NeoPixelSetBrightnessRequest_<ContainerAllocator> Type;

  NeoPixelSetBrightnessRequest_()
    : bright(0)  {
    }
  NeoPixelSetBrightnessRequest_(const ContainerAllocator& _alloc)
    : bright(0)  {
  (void)_alloc;
    }



   typedef uint32_t _bright_type;
  _bright_type bright;




  typedef boost::shared_ptr< ::inmoov_msgs::NeoPixelSetBrightnessRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::inmoov_msgs::NeoPixelSetBrightnessRequest_<ContainerAllocator> const> ConstPtr;

}; // struct NeoPixelSetBrightnessRequest_

typedef ::inmoov_msgs::NeoPixelSetBrightnessRequest_<std::allocator<void> > NeoPixelSetBrightnessRequest;

typedef boost::shared_ptr< ::inmoov_msgs::NeoPixelSetBrightnessRequest > NeoPixelSetBrightnessRequestPtr;
typedef boost::shared_ptr< ::inmoov_msgs::NeoPixelSetBrightnessRequest const> NeoPixelSetBrightnessRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::inmoov_msgs::NeoPixelSetBrightnessRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::inmoov_msgs::NeoPixelSetBrightnessRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace inmoov_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'inmoov_msgs': ['/home/robot/inmoov_ros/src/inmoov_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::inmoov_msgs::NeoPixelSetBrightnessRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::inmoov_msgs::NeoPixelSetBrightnessRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inmoov_msgs::NeoPixelSetBrightnessRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inmoov_msgs::NeoPixelSetBrightnessRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inmoov_msgs::NeoPixelSetBrightnessRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inmoov_msgs::NeoPixelSetBrightnessRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::inmoov_msgs::NeoPixelSetBrightnessRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e52370b2357c85993e6ee817a57e455";
  }

  static const char* value(const ::inmoov_msgs::NeoPixelSetBrightnessRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e52370b2357c859ULL;
  static const uint64_t static_value2 = 0x93e6ee817a57e455ULL;
};

template<class ContainerAllocator>
struct DataType< ::inmoov_msgs::NeoPixelSetBrightnessRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "inmoov_msgs/NeoPixelSetBrightnessRequest";
  }

  static const char* value(const ::inmoov_msgs::NeoPixelSetBrightnessRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::inmoov_msgs::NeoPixelSetBrightnessRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32   bright\n\
";
  }

  static const char* value(const ::inmoov_msgs::NeoPixelSetBrightnessRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::inmoov_msgs::NeoPixelSetBrightnessRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bright);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NeoPixelSetBrightnessRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::inmoov_msgs::NeoPixelSetBrightnessRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::inmoov_msgs::NeoPixelSetBrightnessRequest_<ContainerAllocator>& v)
  {
    s << indent << "bright: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.bright);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INMOOV_MSGS_MESSAGE_NEOPIXELSETBRIGHTNESSREQUEST_H
