// Generated by gencpp from file inmoov_msgs/RPS.msg
// DO NOT EDIT!


#ifndef INMOOV_MSGS_MESSAGE_RPS_H
#define INMOOV_MSGS_MESSAGE_RPS_H

#include <ros/service_traits.h>


#include <inmoov_msgs/RPSRequest.h>
#include <inmoov_msgs/RPSResponse.h>


namespace inmoov_msgs
{

struct RPS
{

typedef RPSRequest Request;
typedef RPSResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RPS
} // namespace inmoov_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::inmoov_msgs::RPS > {
  static const char* value()
  {
    return "9acda9860bc8c37eb184a52b3d4300b0";
  }

  static const char* value(const ::inmoov_msgs::RPS&) { return value(); }
};

template<>
struct DataType< ::inmoov_msgs::RPS > {
  static const char* value()
  {
    return "inmoov_msgs/RPS";
  }

  static const char* value(const ::inmoov_msgs::RPS&) { return value(); }
};


// service_traits::MD5Sum< ::inmoov_msgs::RPSRequest> should match 
// service_traits::MD5Sum< ::inmoov_msgs::RPS > 
template<>
struct MD5Sum< ::inmoov_msgs::RPSRequest>
{
  static const char* value()
  {
    return MD5Sum< ::inmoov_msgs::RPS >::value();
  }
  static const char* value(const ::inmoov_msgs::RPSRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::inmoov_msgs::RPSRequest> should match 
// service_traits::DataType< ::inmoov_msgs::RPS > 
template<>
struct DataType< ::inmoov_msgs::RPSRequest>
{
  static const char* value()
  {
    return DataType< ::inmoov_msgs::RPS >::value();
  }
  static const char* value(const ::inmoov_msgs::RPSRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::inmoov_msgs::RPSResponse> should match 
// service_traits::MD5Sum< ::inmoov_msgs::RPS > 
template<>
struct MD5Sum< ::inmoov_msgs::RPSResponse>
{
  static const char* value()
  {
    return MD5Sum< ::inmoov_msgs::RPS >::value();
  }
  static const char* value(const ::inmoov_msgs::RPSResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::inmoov_msgs::RPSResponse> should match 
// service_traits::DataType< ::inmoov_msgs::RPS > 
template<>
struct DataType< ::inmoov_msgs::RPSResponse>
{
  static const char* value()
  {
    return DataType< ::inmoov_msgs::RPS >::value();
  }
  static const char* value(const ::inmoov_msgs::RPSResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INMOOV_MSGS_MESSAGE_RPS_H
