// Generated by gencpp from file inmoov_msgs/RPSRequest.msg
// DO NOT EDIT!


#ifndef INMOOV_MSGS_MESSAGE_RPSREQUEST_H
#define INMOOV_MSGS_MESSAGE_RPSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace inmoov_msgs
{
template <class ContainerAllocator>
struct RPSRequest_
{
  typedef RPSRequest_<ContainerAllocator> Type;

  RPSRequest_()
    : numOfSamples(0)  {
    }
  RPSRequest_(const ContainerAllocator& _alloc)
    : numOfSamples(0)  {
  (void)_alloc;
    }



   typedef uint8_t _numOfSamples_type;
  _numOfSamples_type numOfSamples;




  typedef boost::shared_ptr< ::inmoov_msgs::RPSRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::inmoov_msgs::RPSRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RPSRequest_

typedef ::inmoov_msgs::RPSRequest_<std::allocator<void> > RPSRequest;

typedef boost::shared_ptr< ::inmoov_msgs::RPSRequest > RPSRequestPtr;
typedef boost::shared_ptr< ::inmoov_msgs::RPSRequest const> RPSRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::inmoov_msgs::RPSRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::inmoov_msgs::RPSRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace inmoov_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'inmoov_msgs': ['/home/robot/inmoov_ros/src/inmoov_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::inmoov_msgs::RPSRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::inmoov_msgs::RPSRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inmoov_msgs::RPSRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inmoov_msgs::RPSRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inmoov_msgs::RPSRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inmoov_msgs::RPSRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::inmoov_msgs::RPSRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "954cb705434c03e209b08b5f31fb6958";
  }

  static const char* value(const ::inmoov_msgs::RPSRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x954cb705434c03e2ULL;
  static const uint64_t static_value2 = 0x09b08b5f31fb6958ULL;
};

template<class ContainerAllocator>
struct DataType< ::inmoov_msgs::RPSRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "inmoov_msgs/RPSRequest";
  }

  static const char* value(const ::inmoov_msgs::RPSRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::inmoov_msgs::RPSRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8  numOfSamples\n\
";
  }

  static const char* value(const ::inmoov_msgs::RPSRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::inmoov_msgs::RPSRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.numOfSamples);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RPSRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::inmoov_msgs::RPSRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::inmoov_msgs::RPSRequest_<ContainerAllocator>& v)
  {
    s << indent << "numOfSamples: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.numOfSamples);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INMOOV_MSGS_MESSAGE_RPSREQUEST_H
