verbose: true
base_link: base_link
models:
 - name: arm
   type: chain
   frame: r_gripper_link
 - name: camera
   type: camera3d
   frame: camera_link
   topic: /camera/depth/points
free_params:
   - waist_pan_joint
   - waist_roll_joint
   - r_shoulder_out_joint
   - r_shoulder_lift_joint
   - r_upper_arm_roll_joint
   - r_elbow_flex_joint
   - r_wrist_roll_joint
free_frames:
 - name: camera_joint
   x: false
   y: false
   z: false
   roll: false
   pitch: true
   yaw: false
error_blocks:
 - name: hand_eye
   type: camera3d_to_arm
   camera: camera
   arm: arm
   joint_scale: 0.0
   position_scale: 0.1
   rotation_scale: 0.1
